---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Start uwsgi service
      systemd:  # Does not seem to work https://github.com/ansible/ansible/pull/23904
          state: started
          name: app

