---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Install "unzip"
      apt:
        name: unzip
    - name: Install "pip"
      apt:
        name: python-pip
    - name: Install "virtualenv"
      pip:
        name: virtualenv
    - name: Install uwsgi service
      copy:
        src=../files/app.service
        dest=/etc/systemd/system
    ### Only needed for Vagrant build ###
    - name: Create ubuntu user
      user: name=ubuntu comment="ubuntu User" groups="sudo,adm"
